Wyb
Iroski/SE-group-90 pull request #93
Opened 2021-05-20 08:35 UTC by SillyPasty

添加模糊搜索功能

2021-05-20 08:36 UTC, SillyPasty commented
请大家注意，如果使用此版本的数据库，因为video格式变化，请在第一次运行前删除本地数据json文件中的video.json，在此运行会自动重新生成 @Iroski @caoyulu @Yuhang-Lu @SexyCrucian @

2021-05-20 13:15 UTC, Iroski requested changes

2021-05-20 13:15 UTC, Iroski commented on documents/document/backend/TinyDbUsage.md
>  #### 删除
这个文档整体改成英文吧 到时候交上去

2021-05-20 13:15 UTC, Iroski commented on src/main/java/model/service/CoachService.java
> +                return new ReturnEntity(CommunicationStatus.VIDEO_NOT_FOUND.getCode(),null);
这为啥是video 应该是coach吧
模糊搜索返回一个空集合是不是也行？ @SexyCrucian

2021-05-20 13:15 UTC, Iroski commented on documents/document/backend/TinyDbUsage.md
>  #### 删除
这个先不急

2021-05-21 01:12 UTC, SillyPasty commented on src/main/java/model/service/CoachService.java
> +                return new ReturnEntity(CommunicationStatus.VIDEO_NOT_FOUND.getCode(),null);
写错了。改好了

2021-05-21 05:43 UTC, SexyCrucian commented on src/main/java/model/service/CoachService.java
> +                return new ReturnEntity(CommunicationStatus.VIDEO_NOT_FOUND.getCode(),null);
空集合也中

2021-05-21 05:48 UTC, Iroski approved these changes

2021-05-21 05:49 UTC, merged